### ISSUE TITLE
Invalid URLs for positive examples

### ISSUE THREAD

**Issue by jackflips** [Clarifai/clarifai-HackMIT#1]
Some of the URLs for positive examples of Phish are malformed. They look like partial URLs or local file paths.

**Comment by jackflips** [comment]
@jimreesman @dankantor

**Comment by jimreesman** [comment]
They're actually ok. They are broken to conform with our line length
convention, but it does make them look weird.

On Fri, Sep 18, 2015 at 12:40 PM, Jack Rogers <notifications@github.com>
wrote:

> @jimreesman <https://github.com/jimreesman> @dankantor
> <https://github.com/dankantor>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Clarifai/clarifai-HackMIT/issues/1#issuecomment-141503413>
> .
>



-- 
Jim Reesman
+1 650 933 7400 | LinkedIn <https://www.linkedin.com/in/jimreesman>

**Comment by jackflips** [comment]
ah, yeah.
